package com.lapsa.insurance.domain;

import com.lapsa.commons.elements.LocalizedElement;

public enum DisplayNameElements implements LocalizedElement {
    CONTACT_DATA,
    CONTACT_DATA_EMPTY,
    //
    COMPANY_CONTACT_PHONE,
    COMPANY_CONTACT_PHONE_EMPTY,
    //
    CALCULATION_DATA,
    CALCULATION_DATA_EMPTY,
    //
    POST_ADDRESS,
    POST_ADDRESS_EMPTY,
    //
    COMPANY_CONTACT_EMAIL,
    COMPANY_CONTACT_EMAIL_EMPTY,
    //
    INSURANCE_PERIOD_DATA,
    INSURANCE_PERIOD_DATA_EMPTY,
    INSURANCE_PERIOD_DATA_FROM,
    INSURANCE_PERIOD_DATA_TILL,
    //
    COMPANY_POINT_OF_SALE,
    COMPANY_POINT_OF_SALE_EMPTY,
    //
    GEO_POINT,
    GEO_POINT_LAT,
    GEO_POINT_LNG,
    //
    DRIVER_LICENSE_DATA,
    DRIVER_LICENSE_DATA_EMPTY,
    DRIVER_LICENSE_DATA_NUMBER,
    DRIVER_LICENSE_DATA_ISSUED,
    //
    IDENTITY_CARD_DATA,
    IDENTITY_CARD_DATA_NUMBER,
    IDENTITY_CARD_DATA_ISSUED,
    //
    ;
}
