package com.lapsa.insurance.domain;

import com.lapsa.commons.elements.LocalizedElement;

public enum DisplayNameElements implements LocalizedElement {
    CONTACT_DATA,
    //
    COMPANY_CONTACT_PHONE,
    COMPANY_CONTACT_PHONE_UNDEFINED,
    //
    CALCULATION_DATA,
    CALCULATION_DATA_UNDEFINED,
    //
    POST_ADDRESS,
    //
    COMPANY_CONTACT_EMAIL,
    COMPANY_CONTACT_EMAIL_UNDEFINED,
    //
    INSURANCE_PERIOD_DATA,
    INSURANCE_PERIOD_DATA_FROM,
    INSURANCE_PERIOD_DATA_TILL,
    //
    COMPANY_POINT_OF_SALE,
    //
    GEO_POINT,
    GEO_POINT_LAT,
    GEO_POINT_LNG,
    //
    DRIVER_LICENSE_DATA,
    DRIVER_LICENSE_DATA_NUMBER,
    DRIVER_LICENSE_DATA_ISSUED,
    //
    IDENTITY_CARD_DATA,
    IDENTITY_CARD_DATA_NUMBER,
    IDENTITY_CARD_DATA_ISSUED,
    //
    VEHICLE_CERTIFICATE_DATA,
    VEHICLE_CERTIFICATE_DATA_NUMBER,
    VEHICLE_CERTIFICATE_DATA_ISSUED,
    VEHICLE_CERTIFICATE_DATA_REGNUMBER,
    ;
}
