-- MIGRATION SCRIPT FROM 1.13 TO 1.14

/*
 * INSURANCE_REQUEST
 */
ALTER TABLE INSURANCE_REQUEST
	ADD COLUMN PAYMENT_METHOD_NAME VARCHAR(255) AFTER PAYMENT_METHOD,
	ADD COLUMN PAYMENT_AMOUNT DOUBLE AFTER PAYMENT_METHOD_NAME,
	CHANGE COLUMN POST_INSTANT PAYMENT_INSTANT DATETIME,
	CHANGE COLUMN POST_REFERENCE PAYMENT_REFERENCE VARCHAR(255),
	CHANGE COLUMN EXTERNAL_ID PAYMENT_INVOICE_NUMBER VARCHAR(255);

ALTER TABLE INSURANCE_REQUEST
	DROP COLUMN PAYMENT_METHOD;

/*
 * VERSION TABLE
 */
DROP TABLE VER_1_13;
CREATE TABLE INSURANCE_VER_1_14 (DUMMY INTEGER NOT NULL, PRIMARY KEY (DUMMY));

