-- MIGRATION SCRIPT FROM 1.13 TO 2.4

/*
 * INSURANCE_REQUEST
 */
ALTER TABLE INSURANCE_REQUEST
	ADD COLUMN PAYMENT_METHOD_NAME VARCHAR(255) AFTER PAYMENT_METHOD,
	ADD COLUMN PAYMENT_AMOUNT DOUBLE AFTER PAYMENT_METHOD_NAME,
	CHANGE COLUMN POST_INSTANT PAYMENT_INSTANT DATETIME,
	CHANGE COLUMN POST_REFERENCE PAYMENT_REFERENCE VARCHAR(255),
	CHANGE COLUMN EXTERNAL_ID PAYMENT_INVOICE_NUMBER VARCHAR(255);

ALTER TABLE INSURANCE_REQUEST
	DROP COLUMN PAYMENT_METHOD;

	
ALTER TABLE IMAGE CHANGE COLUMN ID ID INTEGER AUTO_INCREMENT NOT NULL;

ALTER TABLE DRIVER_LICENSE CHANGE FRONTSIDE_IMAGE_ID FRONTSIDE_IMAGE_ID INTEGER;
ALTER TABLE DRIVER_LICENSE CHANGE BACKSIDE_IMAGE_ID BACKSIDE_IMAGE_ID INTEGER;

ALTER TABLE CASCO_VEHICLE CHANGE VIEW1_IMAGE_ID VIEW1_IMAGE_ID INTEGER;
ALTER TABLE CASCO_VEHICLE CHANGE VIEW2_IMAGE_ID VIEW1_IMAGE_ID INTEGER;
ALTER TABLE CASCO_VEHICLE CHANGE VIEW3_IMAGE_ID VIEW1_IMAGE_ID INTEGER;
ALTER TABLE CASCO_VEHICLE CHANGE VIEW4_IMAGE_ID VIEW1_IMAGE_ID INTEGER;

ALTER TABLE IDENTITY_CARD CHANGE FRONTSIDE_IMAGE_ID FRONTSIDE_IMAGE_ID INTEGER;
ALTER TABLE IDENTITY_CARD CHANGE BACKSIDE_IMAGE_ID BACKSIDE_IMAGE_ID INTEGER;

ALTER TABLE VEHICLE_CERTIFICATE CHANGE FRONTSIDE_IMAGE_ID FRONTSIDE_IMAGE_ID INTEGER;
ALTER TABLE VEHICLE_CERTIFICATE CHANGE BACKSIDE_IMAGE_ID BACKSIDE_IMAGE_ID INTEGER;


/*
 * VERSION TABLE
 */
DROP TABLE VER_1_13;
CREATE TABLE INSURANCE_VER_2_4 (DUMMY INTEGER NOT NULL, PRIMARY KEY (DUMMY));
