-- MIGRATION SCRIPT FROM 1.9 TO 1.10

-- insurance-period

ALTER TABLE CASCO
	 ADD COLUMN PERIOD_FROM DATE AFTER PREMIUM_CURRENCY, 
	 ADD COLUMN PERIOD_TO DATE AFTER PERIOD_FROM;

ALTER TABLE POLICY
	 ADD COLUMN PERIOD_FROM DATE AFTER PREMIUM_CURRENCY, 
	 ADD COLUMN PERIOD_TO DATE AFTER PERIOD_FROM;

/*
 * VERSION TABLE
 */
DROP TABLE VER_1_9;
CREATE TABLE VER_1_10 (DUMMY INTEGER NOT NULL, PRIMARY KEY (DUMMY));
