-- MIGRATION SCRIPT FROM 1.5 TO 1.6

/*
 * CHANGES ON
 * lapsa/insurance-persistence-impl-jpa#8
 */
UPDATE INSURANCE_REQUEST SET REQUESTER_PREFER_LANGUAGE = 'RUSSIAN' WHERE REQUESTER_PREFER_LANGUAGE IS NULL;


/*
 * VERSION TABLE
 */
DROP TABLE VER_1_5;
CREATE TABLE VER_1_6 (DUMMY INTEGER NOT NULL, PRIMARY KEY (DUMMY));
