-- MIGRATION SCRIPT FROM 1.11 TO 1.12

-- phone number as text

-- modify POS_CONTACT_PHONE
ALTER TABLE POS_CONTACT_PHONE
	CHANGE PHONE_NUMBER PHONE_NUMBER2 VARCHAR(255),
	ADD COLUMN PHONE_NUMBER VARCHAR(255) AFTER ID;

UPDATE POS_CONTACT_PHONE SET 
	PHONE_NUMBER = CONCAT('+7 (', PHONE_AREA_CODE, ') ', PHONE_NUMBER2)
	WHERE PHONE_COUNTRY_CODE = 'KZ';

ALTER TABLE POS_CONTACT_PHONE 
	DROP COLUMN PHONE_AREA_CODE,
	DROP COLUMN PHONE_COUNTRY_CODE,
	DROP COLUMN PHONE_NUMBER2;

-- modify REQUEST
ALTER TABLE REQUEST 
	CHANGE REQUESTER_PHONE_NUMBER REQUESTER_PHONE_NUMBER2 VARCHAR(255),
	ADD COLUMN REQUESTER_PHONE_NUMBER VARCHAR(255) AFTER REQUESTER_NAME;

UPDATE REQUEST SET 
	REQUESTER_PHONE_NUMBER = CONCAT('+7 (', REQUESTER_PHONE_AREA_CODE, ') ', REQUESTER_PHONE_NUMBER2)
	WHERE REQUESTER_PHONE_COUNTRY_CODE = 'KZ' OR REQUESTER_PHONE_COUNTRY_CODE = 'RU';

UPDATE REQUEST SET 
	REQUESTER_PHONE_NUMBER = CONCAT('+55 (', REQUESTER_PHONE_AREA_CODE, ') ', REQUESTER_PHONE_NUMBER2)
	WHERE REQUESTER_PHONE_COUNTRY_CODE = 'BR';

UPDATE REQUEST SET 
	REQUESTER_PHONE_NUMBER = CONCAT('+54 (', REQUESTER_PHONE_AREA_CODE, ') ', REQUESTER_PHONE_NUMBER2)
	WHERE REQUESTER_PHONE_COUNTRY_CODE = 'AR';

UPDATE REQUEST SET 
	REQUESTER_PHONE_NUMBER = CONCAT('+64 (', REQUESTER_PHONE_AREA_CODE, ') ', REQUESTER_PHONE_NUMBER2)
	WHERE REQUESTER_PHONE_COUNTRY_CODE = 'NZ';

UPDATE REQUEST SET 
	REQUESTER_PHONE_NUMBER = CONCAT('+1 (', REQUESTER_PHONE_AREA_CODE, ') ', REQUESTER_PHONE_NUMBER2)
	WHERE REQUESTER_PHONE_COUNTRY_CODE = 'US';

UPDATE REQUEST SET 
	REQUESTER_PHONE_NUMBER = CONCAT(REQUESTER_PHONE_COUNTRY_CODE, ' (', REQUESTER_PHONE_AREA_CODE, ') ', REQUESTER_PHONE_NUMBER2)
	WHERE REQUESTER_PHONE_NUMBER IS NULL;

ALTER TABLE REQUEST 
	DROP COLUMN REQUESTER_PHONE_AREA_CODE,
	DROP COLUMN REQUESTER_PHONE_COUNTRY_CODE,
	DROP COLUMN REQUESTER_PHONE_NUMBER2;


-- Agreement number

ALTER TABLE INSURANCE_REQUEST
	ADD COLUMN AGREEMENT_NUMBER VARCHAR(255) AFTER ID; 

/*
 * VERSION TABLE
 */
DROP TABLE VER_1_11;
CREATE TABLE VER_1_12 (DUMMY INTEGER NOT NULL, PRIMARY KEY (DUMMY));
