-- MIGRATION SCRIPT FROM 1.12 TO 1.13

/*
 * user groups
 */
-- table USER_GROUP
CREATE TABLE USER_GROUP (ID INTEGER AUTO_INCREMENT NOT NULL, NAME VARCHAR(255), PRIMARY KEY (ID));
-- table USER_2_GROUP
CREATE TABLE USER_2_GROUP (USER_ID INTEGER NOT NULL, USER_GROUP_ID INTEGER NOT NULL, PRIMARY KEY (USER_ID, USER_GROUP_ID));
ALTER TABLE USER_2_GROUP ADD CONSTRAINT FK_USER_2_GROUP_USER_ID FOREIGN KEY (USER_ID) REFERENCES USER (ID);
ALTER TABLE USER_2_GROUP ADD CONSTRAINT FK_USER_2_GROUP_USER_GROUP_ID FOREIGN KEY (USER_GROUP_ID) REFERENCES USER_GROUP (ID);

/* 
 * inet addr
 */
ALTER TABLE REQUEST
	ADD COLUMN REQUESTER_INET_ADDR VARCHAR(255) AFTER UPDATED,
	ADD COLUMN REQUESTER_INET_HOST VARCHAR(255) AFTER REQUESTER_INET_ADDR; 

/*
 * previous migration issues fix
 */
ALTER TABLE INSURANCE_REQUEST ADD CONSTRAINT `FK_INSURANCE_REQUEST_ID` FOREIGN KEY (`ID`) REFERENCES `REQUEST` (`ID`);
ALTER TABLE POLICY_REQUEST DROP FOREIGN KEY FK_POLICY_REQUEST_ID;
ALTER TABLE POLICY_REQUEST ADD CONSTRAINT `FK_POLICY_REQUEST_ID` FOREIGN KEY (`ID`) REFERENCES `REQUEST` (`ID`);
ALTER TABLE CASCO_REQUEST DROP FOREIGN KEY FK_CASCO_REQUEST_ID;
ALTER TABLE CASCO_REQUEST ADD CONSTRAINT `FK_CASCO_REQUEST_ID` FOREIGN KEY (`ID`) REFERENCES `REQUEST` (`ID`);

/*
 * payment refs
 */
-- rename INSURANCE_REQUEST.PAYMENT_REFERENCE
ALTER TABLE INSURANCE_REQUEST  
	ADD COLUMN EXTERNAL_ID VARCHAR(255) AFTER OBTAINING_PICKUPPOS_ID;
UPDATE INSURANCE_REQUEST SET EXTERNAL_ID = PAYMENT_REFERENCE;
ALTER TABLE INSURANCE_REQUEST
	DROP COLUMN PAYMENT_REFERENCE;

-- add column INSURANCE_REQUEST.POST_INSTANT and INSURANCE_REQUEST.POST_REFERENCE
ALTER TABLE INSURANCE_REQUEST
	ADD COLUMN POST_INSTANT DATETIME AFTER PAYMENT_METHOD,
	ADD COLUMN POST_REFERENCE VARCHAR(255) AFTER POST_INSTANT; 

/*
 * VERSION TABLE
 */
DROP TABLE VER_1_12;
CREATE TABLE VER_1_13 (DUMMY INTEGER NOT NULL, PRIMARY KEY (DUMMY));
