-- MIGRATION SCRIPT FROM 1.12 TO 1.12.1

-- table USER_GROUP
CREATE TABLE USER_GROUP (ID INTEGER AUTO_INCREMENT NOT NULL, NAME VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE USER_2_GROUP (USER_ID INTEGER NOT NULL, USER_GROUP_ID INTEGER NOT NULL, PRIMARY KEY (USER_ID, USER_GROUP_ID));
ALTER TABLE USER_2_GROUP ADD CONSTRAINT FK_USER_2_GROUP_USER_ID FOREIGN KEY (USER_ID) REFERENCES USER (ID);
ALTER TABLE USER_2_GROUP ADD CONSTRAINT FK_USER_2_GROUP_USER_GROUP_ID FOREIGN KEY (USER_GROUP_ID) REFERENCES USER_GROUP (ID);

/*
 * VERSION TABLE
 */
DROP TABLE VER_1_12;
CREATE TABLE VER_1_12_1 (DUMMY INTEGER NOT NULL, PRIMARY KEY (DUMMY));
