-- MIGRATION SCRIPT FROM 1.4 TO 1.5

/*
 * CHANGES ON
 * eurasia36/eurasia36-crm#27
 */

/*
 * TABLE `CASCO`
 */

-- add column ACTUAL_PERMIUM_COST
ALTER TABLE CASCO ADD COLUMN ACTUAL_PERMIUM_COST DOUBLE AFTER PERMIUM_COST;

UPDATE CASCO
   SET CASCO.ACTUAL_PERMIUM_COST = CASCO.PERMIUM_COST WHERE CASCO.ID IN (
	SELECT CASCO_REQUEST.CASCO_ID
	FROM INSURANCE_REQUEST, CASCO_REQUEST
	WHERE INSURANCE_REQUEST.ID = CASCO_REQUEST.ID
	AND INSURANCE_REQUEST.TRANSACTION_STATUS = 'COMPLETED'
);

-- add column CALCULATED_PERMIUM_COST
ALTER TABLE CASCO ADD COLUMN CALCULATED_PERMIUM_COST DOUBLE AFTER ACTUAL_PERMIUM_COST; 
UPDATE CASCO SET CALCULATED_PERMIUM_COST = PERMIUM_COST;

-- add column DISCOUNT_AMOUNT
ALTER TABLE CASCO ADD COLUMN DISCOUNT_AMOUNT DOUBLE AFTER CALCULATED_PERMIUM_COST;

-- remove column PERMIUM_COST
ALTER TABLE CASCO DROP COLUMN PERMIUM_COST; 

/*
 * TABLE `POLICY`
 */

-- add column ACTUAL_PERMIUM_COST
ALTER TABLE POLICY ADD COLUMN ACTUAL_PERMIUM_COST DOUBLE AFTER PERMIUM_COST;

UPDATE POLICY
   SET POLICY.ACTUAL_PERMIUM_COST = POLICY.PERMIUM_COST WHERE POLICY.ID IN (
	SELECT POLICY_REQUEST.POLICY_ID
	FROM INSURANCE_REQUEST, POLICY_REQUEST
	WHERE INSURANCE_REQUEST.ID = POLICY_REQUEST.ID
	AND INSURANCE_REQUEST.TRANSACTION_STATUS = 'COMPLETED'
);

-- add column CALCULATED_PERMIUM_COST
ALTER TABLE POLICY ADD COLUMN CALCULATED_PERMIUM_COST DOUBLE AFTER ACTUAL_PERMIUM_COST; 
UPDATE POLICY SET CALCULATED_PERMIUM_COST = PERMIUM_COST;

-- add column DISCOUNT_AMOUNT
ALTER TABLE POLICY ADD COLUMN DISCOUNT_AMOUNT DOUBLE AFTER CALCULATED_PERMIUM_COST;

-- remove column PERMIUM_COST
ALTER TABLE POLICY DROP COLUMN PERMIUM_COST; 

/*
 * CHANGES ON
 * eurasia36/eurasia36-crm#26
 */

/*
 * TABLE `USER`
 */

-- create table
CREATE TABLE USER (ID INTEGER AUTO_INCREMENT NOT NULL, EMAIL VARCHAR(255), NAME VARCHAR(255), PRIMARY KEY (ID));

/*
 * TABLE `INSURANCE_REQUEST`
 */

-- create column ACCEPTED_BY_USER_ID
ALTER TABLE INSURANCE_REQUEST ADD COLUMN ACCEPTED_BY_USER_ID INTEGER AFTER UTM_TERM;
ALTER TABLE INSURANCE_REQUEST ADD CONSTRAINT FK_INSURANCE_REQUEST_ACCEPTED_BY_USER_ID FOREIGN KEY (ACCEPTED_BY_USER_ID) REFERENCES USER (ID);

-- create column CLOSED_BY_USER_ID
ALTER TABLE INSURANCE_REQUEST ADD COLUMN CLOSED_BY_USER_ID INTEGER AFTER ACCEPTED_BY_USER_ID;
ALTER TABLE INSURANCE_REQUEST ADD CONSTRAINT FK_INSURANCE_REQUEST_CLOSED_BY_USER_ID FOREIGN KEY (CLOSED_BY_USER_ID) REFERENCES USER (ID);

-- create column COMPLETED_BY_USER_ID
ALTER TABLE INSURANCE_REQUEST ADD COLUMN COMPLETED_BY_USER_ID INTEGER AFTER CLOSED_BY_USER_ID;
ALTER TABLE INSURANCE_REQUEST ADD CONSTRAINT FK_INSURANCE_REQUEST_COMPLETED_BY_USER_ID FOREIGN KEY (COMPLETED_BY_USER_ID) REFERENCES USER (ID);

/*
 * CHANGES ON 
 * eurasia36/eurasia36-crm#37
 */

/*
 * TABLE `USER_LOGIN`
 */
CREATE TABLE USER_LOGIN (ID INTEGER AUTO_INCREMENT NOT NULL, NAME VARCHAR(255) UNIQUE, USER_ID INTEGER, PRIMARY KEY (ID));
ALTER TABLE USER_LOGIN ADD CONSTRAINT FK_USER_LOGIN_USER_ID FOREIGN KEY (USER_ID) REFERENCES USER (ID);


/*
 * VERSION TABLE
 */
DROP TABLE VER_1_4;
CREATE TABLE VER_1_5 (DUMMY INTEGER NOT NULL, PRIMARY KEY (DUMMY));
